#!/usr/bin/env node
// Backfill clean slugs for all feed_items rows. Generates:
//   1. Updated `slug` values in Supabase (live mode only)
//   2. `src/lib/slug-redirects.ts` mapping old_slug -> new_slug for 301s
//
// Usage:
//   unset ANTHROPIC_API_KEY && node --env-file=.env scripts/backfill-slugs.mjs           # dry-run
//   unset ANTHROPIC_API_KEY && node --env-file=.env scripts/backfill-slugs.mjs --live    # apply
//
// Idempotent: rerunning after a successful live run produces zero changes.
// Collision handling mirrors insertWithSlugRetry() in refresh-feeds.ts —
// appends -2, -3, ... within the in-memory batch before writing.

import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REDIRECTS_OUT = join(__dirname, '..', 'src', 'lib', 'slug-redirects.ts');

const LIVE = process.argv.includes('--live');
const MAX_LEN = 80;

if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SECRET_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SECRET_KEY. Run with: node --env-file=.env scripts/backfill-slugs.mjs');
  process.exit(2);
}

// Inline copy of titleToSlug — must stay in sync with src/lib/slug.ts.
// Kept inline so this script is dependency-light (no TS compilation needed).
function titleToSlug(title, suffix) {
  let s = title
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\s/g, '-');
  if (s.length > MAX_LEN) s = s.slice(0, MAX_LEN).replace(/-[^-]*$/, '');
  if (suffix) s = `${s}-${suffix}`;
  return s;
}

const supa = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET_KEY);

console.log(`Mode: ${LIVE ? 'LIVE (will write)' : 'DRY-RUN (no writes)'}`);
console.log('Fetching feed_items...\n');

const { data: rows, error } = await supa
  .from('feed_items')
  .select('id, slug, title, created_at')
  .order('created_at', { ascending: true }); // oldest-first so original wins collisions

if (error) {
  console.error('Supabase fetch failed:', error.message);
  process.exit(1);
}

console.log(`Loaded ${rows.length} rows.\n`);

// Plan: for each row, compute clean slug. Handle collisions within batch.
const seen = new Set();
const planned = []; // { id, oldSlug, newSlug, title, changed }

for (const row of rows) {
  let base = titleToSlug(row.title);
  let candidate = base;
  let attempt = 2;
  while (seen.has(candidate)) {
    candidate = `${base}-${attempt}`;
    attempt += 1;
  }
  seen.add(candidate);
  planned.push({
    id: row.id,
    oldSlug: row.slug,
    newSlug: candidate,
    title: row.title,
    changed: row.slug !== candidate
  });
}

const changes = planned.filter(p => p.changed);
console.log(`Planned changes: ${changes.length} of ${planned.length}\n`);

for (const c of changes) {
  console.log(`  ${c.oldSlug}`);
  console.log(`→ ${c.newSlug}`);
  console.log(`  (${c.title.slice(0, 70)})`);
  console.log();
}

if (changes.length === 0) {
  console.log('Nothing to do. Slugs already clean.');
  process.exit(0);
}

if (!LIVE) {
  console.log(`DRY-RUN. To apply, rerun with --live`);
  process.exit(0);
}

// LIVE mode: apply updates one at a time (small batch, ~60 rows max).
console.log('Applying updates...\n');
let applied = 0;
let failed = 0;
for (const c of changes) {
  const { error: updErr } = await supa
    .from('feed_items')
    .update({ slug: c.newSlug })
    .eq('id', c.id);
  if (updErr) {
    console.error(`  FAIL ${c.id}: ${updErr.message}`);
    failed += 1;
  } else {
    applied += 1;
  }
}
console.log(`\nApplied: ${applied}. Failed: ${failed}.\n`);

if (failed > 0) {
  console.error('Some updates failed. Redirects file NOT written. Investigate Supabase errors above.');
  process.exit(1);
}

// Write redirects file.
const redirects = Object.fromEntries(
  changes.map(c => [c.oldSlug, c.newSlug])
);
const generatedAt = new Date().toISOString();
const fileContent = `// Auto-generated by scripts/backfill-slugs.mjs at ${generatedAt}
// Maps old (broken) article slugs to current canonical slugs.
// Consumed by src/pages/news/[slug].astro to serve 301 redirects for inbound
// links from the digest emails / external shares that pointed at the old URLs.
// Do not edit by hand — rerun the backfill script to regenerate.

export const SLUG_REDIRECTS: Record<string, string> = ${JSON.stringify(redirects, null, 2)};
`;
writeFileSync(REDIRECTS_OUT, fileContent);
console.log(`Wrote ${Object.keys(redirects).length} redirect mappings to:\n  ${REDIRECTS_OUT}\n`);
console.log('Backfill complete. Next:');
console.log('  1. Wire SLUG_REDIRECTS into src/pages/news/[slug].astro to serve 301s');
console.log('  2. Commit + deploy');
